config/routes.rb
Chap6::Application.routes.draw do
  resources :students

   root :to => 'students#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :birthday, :body_temperature, :can_send_email, :county, :description, :email, :favorite_time, :graduation_year, :name, :price, :secret
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def human_boolean(boolean)
    boolean ? 'Yes' : 'No'
end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chap6</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :secret %><br />
    <%= f.password_field :secret %>
  </div>
  <div class="field">
  <% counties = {'Buncombe' => 'Bunc', 'Haywood' => 'Hywd', 'Madison' => 'Mad'}%>
<fieldset>
	<legend>County</legend>
	<%= f.radio_button :county, 'Buncombe' %> <%= f.label "county_bunc", "Buncombe" %><br />
	<%= f.radio_button :county, 'Haywood' %> <%= f.label "county_hywd", "Haywood" %><br />
	<%= f.radio_button :county, 'Madison' %> <%= f.label "county_mad", "Madison" %><br />
</fieldset>	
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :can_send_email %><br />
    <%= f.check_box :can_send_email, {:class => 'email'}%>
  </div>

  <div class="field">
	<% graduation_years = {'2010' => '2010', '2011' => '2011', '2012' => '2012', '2013' => '2013', '2014' => '2014', '2015' => '2015', '2016' => '2016', '2017' => '2017', '2018' => '2018' }%>
   <p>
	<%= f.label :graduation_year %><br />
	  <% list = graduation_years.sort %>
	  <%= f.select :graduation_year, list %>
   </p>	
  </div>
  <div class="field">
    <%= f.label :body_temperature %><br />
    <%= f.text_field :body_temperature %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, {:start_year => 1950} %>
  </div>
  <div class="field">
    <%= f.label :favorite_time %><br />
    <%= f.time_select :favorite_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Secret</th>
    <th>County</th>
    <th>Email</th>
    <th>Description</th>
    <th>Can send email</th>
    <th>Graduation year</th>
    <th>Body temperature</th>
    <th>Price</th>
    <th>Birthday</th>
    <th>Favorite time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.secret %></td>
    <td><%= student.county %></td>
    <td><%= student.email %></td>
    <td><%= student.description %></td>
    <td><%= human_boolean(student.can_send_email) %></td>
    <td><%= student.graduation_year %></td>
    <td><%= student.body_temperature %></td>
    <td><%= student.price %></td>
    <td><%= student.birthday %></td>
    <td><%= student.favorite_time %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Secret:</b>
  <%= @student.secret %>
</p>

<p>
  <b>County:</b>
  <%= @student.county %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<p>
  <b>Description:</b>
  <%= @student.description %>
</p>

<p>
  <b>Can send email:</b>
  <%= human_boolean(@student.can_send_email) %>
</p>

<p>
  <b>Graduation year:</b>
  <%= @student.graduation_year %>
</p>

<p>
  <b>Body temperature:</b>
  <%= @student.body_temperature %>
</p>

<p>
  <b>Price:</b>
  <%= @student.price %>
</p>

<p>
  <b>Birthday:</b>
  <%= @student.birthday %>
</p>

<p>
  <b>Favorite time:</b>
  <%= @student.favorite_time %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>